build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:11.0.1
  amd64: ghcr.io/hassio-addons/base/amd64:11.0.1
  armhf: ghcr.io/hassio-addons/base/armhf:11.0.1
  armv7: ghcr.io/hassio-addons/base/armv7:11.0.1
  i386: ghcr.io/hassio-addons/base/i386:11.0.1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ngircd"
  org.opencontainers.image.description: "IRC server."
  org.opencontainers.image.source: "https://github.com/TECH7Fox/Ngircd-add-on"
  org.opencontainers.image.licenses: "MIT"
